# air.toml - Live reload configuration
root = "."
tmp_dir = "./tmp"

[debug]
  interval = 5000
  verbose = true

[build]
  bin = ".tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/server/main.go"
  delay = 2000
  exclude_dir = ["tmp", "vendor", "uploads", "docs", "migrations", "web/static"]
  include_ext = ["go", "mod", "sum", "env", "toml"]
  exclude_regex = ["_test.go"]
  include_dir = ["internal", "cmd", "pkg", "api", "config", "routes"]
  log = "air.log"
  stop_on_error = false  # Continue watching after errors

[color]
  app = "cyan"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "blue"

[log]
  time = true
  level = "debug"

[misc]
  clean_on_exit = false  # Keep files for debugging

[runner]
  env = [
    "DB_HOST=${DB_HOST}",
    "DB_PORT=${DB_PORT}",
    # ... keep other env vars ...
  ]
  args = []
  prepend_cmd = []

[screen]
  clear_on_rebuild = true
  keep_scroll = true